version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1.16.1
jobs:
  build-and-test-backend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          cache-key: backend/package.json
          steps:
            - run: make test-backend
  build-and-test-frontend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          cache-key: frontend/package.json
          steps:
            - run: make test-frontend
  e2e-test:
    executor:
      name: cypress/default
    steps: 
      - checkout
workflows:
  test:
    jobs:
      - build-and-test-backend
      - build-and-test-frontend
      - cypress/run:
          start: make start
          wait-on: http://localhost:3000
          requires:
            - build-and-test-backend
            - build-and-test-frontend
            